### ISSUE TITLE
Error in sub-languages md file

### ISSUE THREAD

**Issue by DoHaiSon** [pfeak/docsify-updated#9]
Hi there,

I'm happy to use your plugin on my website:
[https://dohaison.github.io/InfoSysID](https://dohaison.github.io/InfoSysID)

Everything works fine on the main En page. 
However, I tried to support new languages on my page, e.g., vi-vn. To do that, I created a new branch and put translated markdown file into this branch without `index.html`.
[https://github.com/DoHaiSon/InfoSysID/tree/vi](https://github.com/DoHaiSon/InfoSysID/tree/vi)

All other content works fine but your plugin is not. It appears like this: `last update time: {docsify-updated}`

Could you help me debug this error? The below URL is the repo of my page:
[https://github.com/DoHaiSon/InfoSysID](https://github.com/DoHaiSon/InfoSysID)

Thank you for everything!

**Comment by pfeak** [comment]
Hello, I have completed the test.

It is because the `vi` branch request response does not have a last-modified field, which is also a problem often encountered in rendering failures when deployed on various static website service platforms.

![image](https://github.com/pfeak/docsify-updated/assets/30229826/f9919b09-1f88-4178-aba6-15fc57758151)

If you want to add multi-language documents, it is recommended to store different language documents in different directories of a branch according to the following directory structure.

```
.
└── docs
    ├── README.md
    └── de
        └── README.md
    └── es
        └── README.md
    └── vi
        └── README.md
    └── en
        └── README.md
```

**Comment by DoHaiSon** [comment]
Dear pfeak,

That makes sense. I re-constructed my repo into a single branch, and it worked fine.

Thank you so much!
